name: Publish

on:
  push:
    branches: [master]
    tags: ['*']

jobs:
  publish-scm-1:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup luarocks
        run: sudo apt install -y luarocks

      - name: Setup cjson (required for upload)
        run: luarocks install --local lua-cjson

      - name: Upload rockspec scm-1
        run: luarocks upload --force --api-key=${{ secrets.LUAROCKS_API_KEY }} afl-lua-scm-1.rockspec

  publish-tag:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04
    steps:
      # https://github.com/luarocks/luarocks/wiki/Types-of-rocks
      - uses: actions/checkout@v3

      - name: Setup luarocks
        run: sudo apt install -y luarocks

      # Make a release.
      - run: |
          echo TAG=${GITHUB_REF##*/} >> $GITHUB_ENV
          luarocks new_version --tag ${{ env.TAG }}
          luarocks install afl-lua-${{ env.TAG }}-1.rockspec
          luarocks pack afl-lua-${{ env.TAG }}-1.rockspec

      - name: Upload .rockspec and .src.rock ${{ env.TAG }}
        run: |
            luarocks upload --api-key=${{ secrets.LUAROCKS_API_KEY }} afl-lua-${{ env.TAG }}-1.rockspec
            luarocks upload --api-key=${{ secrets.LUAROCKS_API_KEY }} afl-lua-${{ env.TAG }}-1.src.rock
